// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class S3E3UpdatingMovieTableDates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(S3E3UpdatingMovieTableDates));
        
        string IMigrationMetadata.Id
        {
            get { return "201712281819015_S3E3UpdatingMovieTableDates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
