// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class s3e3LinkingGenreAndMovieTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(s3e3LinkingGenreAndMovieTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201712281910287_s3e3LinkingGenreAndMovieTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
