// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class s3e3AddedGenreDataAgain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(s3e3AddedGenreDataAgain));
        
        string IMigrationMetadata.Id
        {
            get { return "201712282008275_s3e3AddedGenreDataAgain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
